(()=>{
  const scenes=[...document.querySelectorAll('.scene')];const assets=['career-paths-panorama.jpg','career-quest-hero.png','career-video-storyboard.png'];
  scenes.forEach((scene,i)=>{
    if(i>0){const lens=document.createElement('div');lens.className='career-lens';const steps=lensSteps(scene);lens.innerHTML=steps.map((x,n)=>`<span><i>${n+1}</i>${x}</span>`).join('');const title=scene.querySelector('h2');title?.insertAdjacentElement('afterend',lens)}
    if(i>0&&!scene.querySelector('img')){const mode=i%3;const variants=['career-wide','career-left','career-right'];const asset=mode===0?assets[0]:assets[mode];const fig=document.createElement('figure');fig.className=`career-film ${variants[mode]}`;if(i===5)scene.classList.add('career-corner');fig.innerHTML=`<img src="assets/${asset}" alt="Career workplace and transferable-skills visual evidence."><figcaption>${caption(scene)}</figcaption>`;const lens=scene.querySelector('.career-lens');const content=scene.querySelector('.grid,.board,.story-grid,.formula,.feedback,.notice');if(mode===0&&lens)lens.after(fig);else if(mode===1&&content)content.after(fig);else if(scene.querySelector('.notice,.feedback'))scene.querySelector('.notice,.feedback').before(fig);else if(content)content.before(fig);else lens?.after(fig)}
  });
  const toolbar=document.querySelector('.toolbar');const info=document.createElement('button');info.id='v2Info';info.className='v2-control';info.textContent='i · task';const full=document.createElement('button');full.id='v2Full';full.className='v2-control';full.textContent='⛶ · full screen';toolbar?.append(info,full);
  const panel=document.createElement('section');panel.className='v2-panel';panel.innerHTML='<div class="v2-panel-card"><button class="v2-close" aria-label="Close task panel">×</button><h3>Career task</h3><p class="v2-note"></p><ol><li>Collect one visible or spoken clue.</li><li>Connect it to a job, workplace, or skill.</li><li>Explain why it matters and ask one follow-up.</li></ol></div>';document.body.append(panel);
  const open=()=>{const s=document.querySelector('.scene.active');panel.querySelector('h3').textContent=s?.dataset.title||'Career task';panel.querySelector('.v2-note').textContent=s?.querySelector('.teacher')?.textContent.trim()||caption(s);panel.classList.add('open')};info.onclick=open;panel.querySelector('.v2-close').onclick=()=>panel.classList.remove('open');panel.onclick=e=>{if(e.target===panel)panel.classList.remove('open')};full.onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='i')open();if(e.key==='Escape')panel.classList.remove('open')});
  function lensSteps(s){const t=s?.dataset.title||'';if(/Watch|viewing|Comprehension/.test(t))return['Observe one concrete detail','Record evidence, not a guess','Explain what the clue means'];if(/Speaking|Interview|gap/i.test(t))return['Choose a role or question','Answer with a reason','Ask one follow-up'];if(/Production|Gallery/i.test(t))return['Build a clear career idea','Add workplace + two skills','Present and receive evidence-based feedback'];if(/Vocabulary|Skills|Pronunciation/i.test(t))return['Notice the word or stress','Connect it to a workplace','Use it in a complete sentence'];return['Study the prompt or visual','Make one supported choice','Share a complete reason']}
  function caption(s){const t=s?.dataset.title||'';if(/Watch|viewing/.test(t))return'Pause the documentary frame and collect evidence.';if(/Skills|Vocabulary/.test(t))return'Jobs use knowledge, tools, and transferable human skills.';if(/Speaking|Production/.test(t))return'Ask, listen, connect the evidence, and report.';return'Look beyond the job title: workplace, action, skill, and impact.'}
})();
