(()=>{
  const scenes=[...document.querySelectorAll('.scene')];
  const assets=['future-postcards-hero.png','future-trip-story.png','future-window-speaking.png'];
  const captions=['Name the action you can see in progress.','Place the camera at one exact future moment.','Use the picture to create a moving future scene.'];
  scenes.forEach((scene,i)=>{
    let t;if(i>0){t=document.createElement('div');t.className='task-ticket';t.innerHTML='<b>Task</b><span>'+taskText(scene)+'</span>';const lead=scene.querySelector('.lead');(lead||scene.querySelector('.board'))?.insertAdjacentElement('afterend',t)}
    if(i>0&&!scene.querySelector('img')&&!scene.querySelector('#bagZone')){const mode=i%3;const variants=['postcard-wide','postcard-left','postcard-right'];const fig=document.createElement('figure');fig.className=`travel-visual ${variants[mode]}`;fig.innerHTML=`<img src="assets/${assets[i%3]}" alt="Travel scene for a Future Continuous speaking or grammar task."><figcaption>${captions[i%3]}</figcaption>`;const content=scene.querySelector('.grid,.luggage,.camera,.tabs,.panel,.feedback');if(mode===0&&t)t.after(fig);else if(mode===1&&content)content.after(fig);else if(scene.querySelector('.feedback'))scene.querySelector('.feedback').before(fig);else if(content)content.before(fig);else t?.after(fig)}
  });
  const bag=document.querySelector('#bagZone');if(bag&&!bag.querySelector('img'))bag.insertAdjacentHTML('afterbegin','<img src="assets/future-trip-story.png" alt="Travellers actively waiting, searching and moving during a journey.">');
  let chosen=new Set();document.querySelectorAll('#sortGrid .sort-card').forEach(card=>card.onclick=()=>{const action=card.dataset.kind==='action';card.classList.remove('selected','good','bad');card.classList.add(action?'good':'bad');if(action)chosen.add(card);document.querySelector('#sortFeedback').textContent=action?`Correct action tag. Score: ${chosen.size} / 2`:'Not this one: it is an object, not an action in progress.';document.querySelector('#sortFeedback').classList.toggle('good',chosen.size===2);document.querySelector('#sortFeedback').classList.toggle('warn',!action)});
  const controls=document.querySelector('.controls');const next=document.querySelector('#next');
  const info=document.createElement('button');info.id='v2Info';info.className='nav v2-control';info.textContent='i · INFO';info.setAttribute('aria-label','Open task instructions');const full=document.createElement('button');full.id='v2Full';full.className='nav v2-control';full.textContent='⛶ · FULL';full.setAttribute('aria-label','Toggle fullscreen');controls?.insertBefore(info,next);controls?.insertBefore(full,next);
  const panel=document.createElement('section');panel.className='v2-panel';panel.innerHTML='<div class="v2-panel-card"><button class="v2-close" aria-label="Close task panel">×</button><h3 id="v2PanelTitle">Travel task</h3><p id="v2PanelNote"></p><ol><li>Study the picture, example, or time stamp.</li><li>Choose, build, repair, or discuss.</li><li>Say the complete sentence and explain the time relationship.</li></ol></div>';document.body.append(panel);
  const open=()=>{const s=document.querySelector('.scene.active');panel.querySelector('h3').textContent=s?.dataset.title||'Travel task';panel.querySelector('p').textContent=s?.querySelector('.teacher')?.textContent.trim()||taskText(s);panel.classList.add('open')};info.onclick=open;panel.querySelector('.v2-close').onclick=()=>panel.classList.remove('open');panel.onclick=e=>{if(e.target===panel)panel.classList.remove('open')};full.onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='i')open();if(e.key==='Escape')panel.classList.remove('open')});
  const counter=document.querySelector('#counter'),fill=document.querySelector('#fill');const sync=()=>{const n=parseInt(counter?.textContent)||1;fill?.style.setProperty('width',(n/scenes.length*100)+'%','important');fill?.style.setProperty('height','100%','important')};new MutationObserver(sync).observe(counter,{childList:true,subtree:true,characterData:true});sync();
  function taskText(scene){if(!scene)return'';if(scene.querySelector('#sortGrid'))return'Choose only the two visible actions. Objects are distractors.';if(scene.querySelector('.tabs'))return'Open each form, read the pattern, then transform one sentence.';if(scene.querySelector('.option,.quiz-option'))return'Choose one answer per question and justify it using the future time clue.';if(scene.querySelector('.timer'))return'Build a four-stop future day, rehearse, then present without reading.';if(scene.querySelector('mark'))return'Tap the highlighted forms and describe the future scene they create.';return'Use the visual clue to make one complete Future Continuous sentence.'}
})();
