from pathlib import Path
import re

P = Path(r'C:\Users\doktu\WorkBuddy AI\2026-08-06-20-15-34\outputs\lesson-preint2-revision-mobile.html')
s = P.read_text(encoding='utf-8')

EXTRAS = {
    '3': '''<div class="teach-zone objectives-zone"><div class="zone-label"><i class="fas fa-rocket"></i> Today’s mission</div><div class="mission-track"><div class="mission-step active"><b>1</b><span>Notice</span><small>spot the time clue</small></div><div class="mission-line"></div><div class="mission-step"><b>2</b><span>Choose</span><small>pick the tense</small></div><div class="mission-line"></div><div class="mission-step"><b>3</b><span>Use</span><small>say your sentence</small></div></div><div class="teacher-tip"><i class="fas fa-lightbulb"></i><span><strong>Teacher tip:</strong> Ask students to point to the time clue before they answer.</span></div></div>''',
    '10': '''<div class="teach-zone gap-side"><div class="zone-label"><i class="fas fa-compass"></i> Tense finder</div><div class="tense-map"><button class="tense-chip simple" onclick="showTenseHint('simple')">every day</button><button class="tense-chip continuous" onclick="showTenseHint('continuous')">look!</button><button class="tense-chip past" onclick="showTenseHint('past')">last week</button><button class="tense-chip future" onclick="showTenseHint('future')">I think…</button><button class="tense-chip perfect" onclick="showTenseHint('perfect')">ever / never</button><button class="tense-chip place" onclick="showTenseHint('place')">there is / are</button></div><div id="tenseHint" class="hint-bubble"><i class="fas fa-hand-pointer"></i> Click a clue for a quick reminder.</div><div class="mini-timer"><span><i class="fas fa-clock"></i> Class timer</span><strong id="timerValue">01:00</strong><button class="timer-btn" onclick="toggleLessonTimer()" id="timerBtn">Start</button></div></div>''',
    '13': '''<div class="teach-zone speaking-zone"><div class="zone-label"><i class="fas fa-microphone"></i> Speaking mission</div><div class="speaking-flow"><div><b>Ask</b><small>one question</small></div><span>→</span><div><b>Listen</b><small>for a tense</small></div><span>→</span><div><b>Report</b><small>one fact</small></div></div><div class="teacher-tip"><i class="fas fa-comments"></i><span>Challenge: use <strong>one past</strong>, <strong>one present</strong>, and <strong>one future</strong> question.</span></div></div>''',
    '14': '''<div class="teach-zone production-zone"><div class="zone-label"><i class="fas fa-stopwatch"></i> 2-minute rehearsal</div><div class="rehearsal"><div class="rehearsal-ring"><span id="rehearsalValue">2:00</span><small>minutes</small></div><div class="rehearsal-copy"><strong>Plan → Speak → Improve</strong><span>Use the timeline on the left as your speaking path.</span><button class="bt bt1" onclick="toggleRehearsal()" id="rehearsalBtn"><i class="fas fa-play"></i> Start rehearsal</button></div></div></div>''',
    '16': '''<div class="teach-zone recap-zone"><div class="zone-label"><i class="fas fa-sort"></i> Sort the clues</div><div class="sort-row"><button onclick="sortClue(this,'past')">yesterday</button><button onclick="sortClue(this,'now')">right now</button><button onclick="sortClue(this,'perfect')">since 2020</button><button onclick="sortClue(this,'future')">next week</button></div><div id="sortFeedback" class="sort-feedback">Click a clue, then say the tense it belongs to.</div></div>''',
    '18': '''<div class="teach-zone progress-zone"><div class="zone-label"><i class="fas fa-chart-line"></i> Your learning streak</div><div class="streak-bars"><div><i style="height:42%"></i><span>Know</span></div><div><i style="height:68%"></i><span>Choose</span></div><div><i style="height:88%"></i><span>Use</span></div><div><i class="today" style="height:100%"></i><span>Today</span></div></div><p><strong>Every checked task is evidence of progress.</strong> Tick one after each practice round.</p></div>''',
    '19': '''<div class="teach-zone exit-zone"><div class="zone-label"><i class="fas fa-heart"></i> How confident do you feel?</div><div class="confidence" role="group" aria-label="Confidence rating"><button onclick="rateConfidence(this,'Starting')">🌱<span>Starting</span></button><button onclick="rateConfidence(this,'Growing')">🌿<span>Growing</span></button><button onclick="rateConfidence(this,'Ready')">🌳<span>Ready</span></button></div><div id="confidenceNote" class="sort-feedback">Choose one before you leave.</div></div>'''
}

for slide, extra in EXTRAS.items():
    marker = 'class="' + {'3':'objectives-zone','10':'gap-side','13':'speaking-zone','14':'production-zone','16':'recap-zone','18':'progress-zone','19':'exit-zone'}[slide] + '"'
    if marker in s:
        continue
    start_token = f'<div class="sc hs" data-slide="{slide}">'
    start = s.find(start_token)
    if start < 0:
        raise SystemExit(f'slide {slide} not found')
    end = s.find('<!--', start)
    if end < 0:
        end = s.find('<script>', start)
    block = s[start:end]
    close = block.rfind('</div></div>')
    if close < 0:
        raise SystemExit(f'slide {slide} closing boundary not found')
    block = block[:close] + extra + block[close:]
    s = s[:start] + block + s[end:]

CSS = r'''
/* ===== Purposeful whitespace + teaching zones ===== */
.teach-zone{border:2px solid #E2E8F0;border-radius:18px;background:rgba(255,255,255,.72);padding:18px 22px;margin-top:18px;animation:zoneIn .55s ease both}.zone-label{font-family:'Nunito',sans-serif;font-size:16px;font-weight:900;color:var(--dark);display:flex;align-items:center;gap:8px;margin-bottom:12px}.zone-label i{color:var(--teal)}
@keyframes zoneIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}
.mission-track{display:flex;align-items:center;justify-content:center;gap:12px}.mission-step{display:grid;grid-template-columns:34px 1fr;column-gap:8px;align-items:center}.mission-step b{grid-row:1/3;width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#E2E8F0;color:var(--mid);font-family:'Nunito',sans-serif}.mission-step.active b{background:var(--teal);color:#fff;animation:pulseSoft 1.8s ease-in-out infinite}.mission-step span{font-weight:800}.mission-step small{color:var(--mid)}.mission-line{height:3px;flex:1;max-width:100px;background:linear-gradient(90deg,var(--teal-l),var(--amber-l));border-radius:3px}.teacher-tip{display:flex;align-items:center;gap:10px;margin-top:14px;padding:10px 12px;border-radius:12px;background:#F8FAFC;color:var(--mid);font-size:14px}.teacher-tip i{color:var(--amber);font-size:18px}@keyframes pulseSoft{0%,100%{box-shadow:0 0 0 0 rgba(13,148,136,.25)}50%{box-shadow:0 0 0 9px rgba(13,148,136,0)}}
.gap-side{display:flex;flex-direction:column;justify-content:center;min-height:360px;background:linear-gradient(145deg,#F0FDFA,#F8FAFC);border-color:#99F6E4}.tense-map{display:grid;grid-template-columns:1fr 1fr;gap:10px}.tense-chip{border:0;border-radius:12px;padding:12px 10px;text-align:left;font-family:'Nunito',sans-serif;font-weight:800;cursor:pointer;color:var(--dark);transition:.2s}.tense-chip:hover{transform:translateY(-2px)}.tense-chip.simple{background:var(--teal-l);color:var(--teal-d)}.tense-chip.continuous{background:var(--amber-l);color:#92400E}.tense-chip.past{background:var(--coral-l);color:#BE123C}.tense-chip.future{background:var(--grn-l);color:#065F46}.tense-chip.perfect{background:var(--blu-l);color:#0369A1}.tense-chip.place{background:var(--pur-l);color:#6D28D9}.hint-bubble{min-height:50px;margin-top:14px;border-radius:12px;background:#fff;border:2px dashed #BAE6FD;padding:12px;color:#0369A1;font-size:14px}.mini-timer{margin-top:14px;border-top:1px solid #D1FAE5;padding-top:12px;display:flex;align-items:center;gap:10px}.mini-timer span{color:var(--mid);font-weight:700}.mini-timer strong{font-family:'Nunito',sans-serif;color:var(--teal);font-size:22px;margin-left:auto}.timer-btn{border:0;border-radius:9px;background:var(--teal);color:#fff;padding:8px 13px;font-weight:800;cursor:pointer}
.speaking-zone,.production-zone,.recap-zone,.progress-zone,.exit-zone{background:linear-gradient(135deg,rgba(255,255,255,.88),rgba(240,253,250,.78));border-color:#99F6E4}.speaking-flow{display:flex;align-items:center;justify-content:center;gap:18px}.speaking-flow>div{display:flex;flex-direction:column;align-items:center;gap:2px;padding:10px 22px;border-radius:14px;background:#F0FDFA;border:1px solid #99F6E4}.speaking-flow b{font-family:'Nunito',sans-serif;color:var(--teal-d);font-size:18px}.speaking-flow small{color:var(--mid)}.speaking-flow>span{color:var(--amber);font-size:24px;font-weight:900}.rehearsal{display:flex;align-items:center;gap:22px}.rehearsal-ring{width:110px;height:110px;border-radius:50%;display:flex;flex-direction:column;align-items:center;justify-content:center;border:9px solid var(--teal-l);outline:3px solid var(--teal);background:#fff;font-family:'Nunito',sans-serif;color:var(--teal-d)}.rehearsal-ring span{font-size:25px;font-weight:900}.rehearsal-ring small{color:var(--mid)}.rehearsal-copy{display:flex;flex-direction:column;gap:6px}.rehearsal-copy strong{font-family:'Nunito',sans-serif;font-size:18px}.rehearsal-copy span{color:var(--mid)}.sort-row{display:flex;gap:10px;flex-wrap:wrap}.sort-row button{border:0;border-radius:10px;background:#fff;padding:10px 14px;color:var(--dark);font-weight:800;cursor:pointer;box-shadow:0 2px 6px rgba(15,23,42,.08);transition:.2s}.sort-row button:hover,.sort-row button.sorted{background:var(--teal);color:#fff;transform:translateY(-2px)}.sort-feedback{margin-top:10px;color:var(--mid);font-size:14px;min-height:20px}.streak-bars{height:120px;display:flex;align-items:end;gap:22px;padding:0 12px;border-bottom:2px solid #CBD5E1}.streak-bars>div{flex:1;height:100%;display:flex;flex-direction:column;justify-content:end;align-items:center;gap:5px;color:var(--mid);font-size:12px}.streak-bars i{display:block;width:42px;max-width:100%;background:linear-gradient(180deg,var(--teal),var(--teal-l));border-radius:8px 8px 0 0}.streak-bars i.today{background:linear-gradient(180deg,var(--amber),#FDE68A);animation:barPulse 1.8s ease-in-out infinite}.progress-zone p{margin-top:12px;color:var(--mid);text-align:center}@keyframes barPulse{0%,100%{transform:scaleY(1);transform-origin:bottom}50%{transform:scaleY(.88);transform-origin:bottom}}.confidence{display:flex;justify-content:center;gap:18px}.confidence button{border:2px solid #E2E8F0;border-radius:14px;background:#fff;padding:12px 22px;cursor:pointer;display:flex;flex-direction:column;align-items:center;gap:4px;font-size:28px;transition:.2s}.confidence button span{font-family:'Nunito',sans-serif;font-size:14px;font-weight:800;color:var(--dark)}.confidence button:hover,.confidence button.selected{border-color:var(--teal);background:var(--teal-l);transform:translateY(-3px)}
@media(min-width:901px) and (min-aspect-ratio:4/3){.teach-zone{margin-top:12px;padding:14px 18px}.gap-side{min-height:0;height:100%;margin-top:0}.zone-label{font-size:17px;margin-bottom:9px}.teacher-tip{margin-top:9px;padding:8px 10px}.mission-track{gap:9px}.mission-step small{font-size:12px}.gap-side .tense-chip{padding:10px}.gap-side .hint-bubble{margin-top:10px}.streak-bars{height:105px}}
@media(max-width:900px){.mission-track,.speaking-flow{flex-wrap:wrap}.mission-line{display:none}.gap-side{min-height:0}.rehearsal{justify-content:center}.confidence{gap:8px}.confidence button{padding:9px 14px}.streak-bars{gap:12px}}
'''
s = s.replace('</style>', CSS + '\n</style>', 1)

JS = r'''
// ===== Teaching zones: timers, clue map, confidence and sorting =====
let lessonTimer=null,lessonSeconds=60,rehearsalTimer=null,rehearsalSeconds=120;
function fmtTime(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function toggleLessonTimer(){const btn=document.getElementById('timerBtn');if(lessonTimer){clearInterval(lessonTimer);lessonTimer=null;if(btn)btn.textContent='Resume';return}if(lessonSeconds<=0)lessonSeconds=60;if(btn)btn.textContent='Pause';lessonTimer=setInterval(()=>{lessonSeconds--;const el=document.getElementById('timerValue');if(el)el.textContent=fmtTime(lessonSeconds);if(lessonSeconds<=0){clearInterval(lessonTimer);lessonTimer=null;if(btn)btn.textContent='Start';tS('<i class="fas fa-flag-checkered"></i> Time! Check your answers');}},1000)}
function showTenseHint(k){const hints={simple:'Present Simple: look for a routine or repeated action. Example: I wake up at 7.',continuous:'Present Continuous: look for an action happening now. Example: It is snowing.',past:'Past Simple: a finished action with a past time. Example: We went last Saturday.',future:'Future Simple: a prediction or idea about later. Example: She will love it.',perfect:'Present Perfect: life experience or a past action connected to now. Example: He has never been there.',place:'There is/are: use is for one thing and are for two or more.'};const e=document.getElementById('tenseHint');if(e)e.innerHTML='<i class="fas fa-lightbulb"></i> '+hints[k]}
function toggleRehearsal(){const b=document.getElementById('rehearsalBtn');if(rehearsalTimer){clearInterval(rehearsalTimer);rehearsalTimer=null;if(b)b.innerHTML='<i class="fas fa-play"></i> Resume';return}if(rehearsalSeconds<=0)rehearsalSeconds=120;if(b)b.innerHTML='<i class="fas fa-pause"></i> Pause';rehearsalTimer=setInterval(()=>{rehearsalSeconds--;const e=document.getElementById('rehearsalValue');if(e)e.textContent=fmtTime(rehearsalSeconds);if(rehearsalSeconds<=0){clearInterval(rehearsalTimer);rehearsalTimer=null;if(b)b.innerHTML='<i class="fas fa-redo"></i> Restart';tS('<i class="fas fa-microphone"></i> Time to present!')}},1000)}
function sortClue(btn,k){document.querySelectorAll('.sort-row button').forEach(x=>x.classList.remove('sorted'));btn.classList.add('sorted');const names={past:'Past Simple',now:'Present Continuous',perfect:'Present Perfect',future:'Future Simple'};const e=document.getElementById('sortFeedback');if(e)e.innerHTML='<i class="fas fa-check" style="color:var(--grn)"></i> '+btn.textContent+' → <strong>'+names[k]+'</strong>'}
function rateConfidence(btn,label){document.querySelectorAll('.confidence button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');const e=document.getElementById('confidenceNote');if(e)e.innerHTML='<i class="fas fa-check" style="color:var(--grn)"></i> You feel <strong>'+label+'</strong> — nice reflection!'}
'''
s = s.replace('\n</script>', JS + '\n</script>', 1)
P.write_text(s, encoding='utf-8')
print('enhanced teaching zones and layout')
