from pathlib import Path
import re

p = Path(r'C:\Users\doktu\WorkBuddy AI\2026-08-06-20-15-34\outputs\lesson-preint2-revision-mobile.html')
s = p.read_text(encoding='utf-8')

visuals = {
'6': '''<div class="grammar-visual" data-tl="g6"><div class="grammar-visual-title"><span class="grammar-number">01</span><span>When does it happen?</span><span class="grammar-hint">routine vs right now</span></div><svg viewBox="0 0 1200 250" role="img" aria-label="Present Simple repeats across time while Present Continuous happens around now"><line x1="220" y1="72" x2="1140" y2="72" stroke="#0D9488" stroke-width="8" stroke-linecap="round"/><circle cx="300" cy="72" r="13" fill="#0D9488"/><circle cx="470" cy="72" r="13" fill="#0D9488"/><circle cx="640" cy="72" r="13" fill="#0D9488"/><circle cx="810" cy="72" r="13" fill="#0D9488"/><circle cx="980" cy="72" r="13" fill="#0D9488"/><text x="28" y="80" font-family="Arial" font-size="25" font-weight="700" fill="#0F766E">Present Simple</text><text x="250" y="116" font-family="Arial" font-size="21" fill="#475569">always · usually · every day · repeated habit</text><line x1="220" y1="180" x2="1140" y2="180" stroke="#F59E0B" stroke-width="8" stroke-dasharray="3 22" stroke-linecap="round"/><circle cx="1010" cy="180" r="28" fill="#F59E0B"/><text x="1010" y="188" text-anchor="middle" font-family="Arial" font-size="17" font-weight="700" fill="#fff">NOW</text><text x="28" y="188" font-family="Arial" font-size="25" font-weight="700" fill="#92400E">Present Continuous</text><text x="250" y="224" font-family="Arial" font-size="21" fill="#475569">now · at the moment · happening temporarily</text></svg></div>''',
'7': '''<div class="grammar-visual" data-tl="g7"><div class="grammar-visual-title"><span class="grammar-number">02</span><span>Where is the action?</span><span class="grammar-hint">finished past vs future idea</span></div><svg viewBox="0 0 1200 230" role="img" aria-label="Past Simple is before now and Future Simple is after now"><line x1="70" y1="120" x2="1130" y2="120" stroke="#1E293B" stroke-width="7" stroke-linecap="round"/><polygon points="1130,120 1100,104 1100,136" fill="#1E293B"/><rect x="90" y="82" width="390" height="76" rx="18" fill="#FFE4E6"/><text x="285" y="117" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700" fill="#BE123C">Past Simple</text><text x="285" y="145" text-anchor="middle" font-family="Arial" font-size="19" fill="#BE123C">finished: yesterday / last year</text><circle cx="600" cy="120" r="22" fill="#1E293B"/><text x="600" y="174" text-anchor="middle" font-family="Arial" font-size="22" font-weight="700" fill="#1E293B">NOW</text><rect x="720" y="82" width="390" height="76" rx="18" fill="#D1FAE5"/><text x="915" y="117" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700" fill="#065F46">Future Simple</text><text x="915" y="145" text-anchor="middle" font-family="Arial" font-size="19" fill="#065F46">will: tomorrow / next summer</text><text x="300" y="45" text-anchor="middle" font-family="Arial" font-size="21" fill="#BE123C">← before now</text><text x="900" y="45" text-anchor="middle" font-family="Arial" font-size="21" fill="#065F46">after now →</text></svg></div>''',
'8': '''<div class="grammar-visual" data-tl="g8"><div class="grammar-visual-title"><span class="grammar-number">03</span><span>Why does it connect?</span><span class="grammar-hint">past experience → present</span></div><svg viewBox="0 0 1200 230" role="img" aria-label="Present Perfect connects an unspecified past event with the present"><text x="30" y="45" font-family="Arial" font-size="25" font-weight="700" fill="#0369A1">Present Perfect</text><text x="30" y="82" font-family="Arial" font-size="19" fill="#475569">have / has + past participle (V3)</text><line x1="230" y1="140" x2="1110" y2="140" stroke="#0EA5E9" stroke-width="8" stroke-linecap="round"/><circle cx="320" cy="140" r="18" fill="#0284C7"/><text x="320" y="190" text-anchor="middle" font-family="Arial" font-size="20" font-weight="700" fill="#0369A1">past event</text><rect x="320" y="112" width="790" height="56" rx="28" fill="#BAE6FD" opacity=".65"/><circle cx="1110" cy="140" r="28" fill="#0EA5E9"/><text x="1110" y="148" text-anchor="middle" font-family="Arial" font-size="16" font-weight="700" fill="#fff">NOW</text><text x="695" y="104" text-anchor="middle" font-family="Arial" font-size="21" fill="#0369A1">since 2020 · for 3 years · unfinished time</text><text x="695" y="218" text-anchor="middle" font-family="Arial" font-size="21" fill="#0369A1">ever · never · just · already · yet</text></svg></div>''',
'9': '''<div class="grammar-visual" data-tl="g9"><div class="grammar-visual-title"><span class="grammar-number">04</span><span>Three useful grammar pictures</span><span class="grammar-hint">count · compare · predict</span></div><div class="grammar-visual-grid"><div class="gv-mini gv-purple"><strong>There is / are</strong><div class="dot-row"><i></i><i></i><i></i></div><small>1 thing = there is<br>2+ things = there are</small></div><div class="gv-mini gv-amber"><strong>Comparatives</strong><div class="bar-row"><i></i><i></i></div><small>small → smaller<br>beautiful → more beautiful</small></div><div class="gv-mini gv-teal"><strong>First Conditional</strong><div class="if-flow"><span>If + Present</span><b>→</b><span>will + V</span></div><small>If it rains, we will stay home.</small></div></div></div>'''
}

# Replace each entire prior visual card by using its unique marker through closing card div.
for n, replacement in visuals.items():
    pat = re.compile(r'<div class="(?:cd|grammar-visual)" data-tl="g' + n + r'"[\s\S]*?</svg>\s*</div>|<div class="(?:cd|grammar-visual)" data-tl="g' + n + r'"[\s\S]*?</div>\s*</div>', re.I)
    s, count = pat.subn(replacement, s, count=1)
    if count != 1:
        raise SystemExit(f'Could not replace visual g{n}; matches={count}')

css = '''
/* ===== Consistent grammar visual system ===== */
.grammar-visual{margin-top:18px;background:#F8FAFC;border:2px solid #CBD5E1;border-radius:18px;padding:18px 22px;overflow:hidden;flex:none}
.grammar-visual-title{display:flex;align-items:center;gap:10px;color:var(--dark);font-family:'Nunito',sans-serif;font-weight:900;font-size:18px;margin-bottom:10px}
.grammar-number{display:inline-flex;align-items:center;justify-content:center;width:32px;height:32px;border-radius:10px;background:var(--dark);color:#fff;font-size:13px}
.grammar-hint{margin-left:auto;color:var(--mid);font-family:'Source Sans 3',sans-serif;font-size:14px;font-weight:600}
.grammar-visual svg{display:block;width:100%;height:auto;min-height:155px}
.grammar-visual-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
.gv-mini{min-height:130px;border-radius:14px;padding:16px;display:flex;flex-direction:column;gap:9px;font-size:16px}
.gv-mini strong{font-family:'Nunito',sans-serif;font-size:18px}.gv-mini small{font-size:14px;line-height:1.35}.gv-purple{background:#F5F3FF;color:#6D28D9;border:1px solid #DDD6FE}.gv-amber{background:#FFFBEB;color:#92400E;border:1px solid #FDE68A}.gv-teal{background:#F0FDFA;color:#0F766E;border:1px solid #99F6E4}
.dot-row,.bar-row{height:42px;display:flex;align-items:end;gap:9px}.dot-row i{width:20px;height:20px;border-radius:50%;background:#8B5CF6}.bar-row i{width:28px;border-radius:5px 5px 0 0;background:#F59E0B;height:26px}.bar-row i+ i{height:42px;background:#D97706}
.if-flow{display:flex;align-items:center;gap:7px;font-weight:800;font-size:14px}.if-flow span{background:#CCFBF1;padding:8px;border-radius:8px}.if-flow b{font-size:20px}
@media(max-width:900px){.grammar-visual{padding:14px;margin-top:14px}.grammar-visual-title{font-size:16px}.grammar-hint{display:none}.grammar-visual svg{min-height:0}.grammar-visual-grid{grid-template-columns:1fr;gap:8px}.gv-mini{min-height:0;padding:12px}.gv-mini strong{font-size:16px}.gv-mini small{font-size:13px}.dot-row,.bar-row{height:28px}.if-flow{font-size:12px}}
'''
s = s.replace('</style>', css + '\n</style>', 1)
p.write_text(s, encoding='utf-8')
print('rewrote grammar visuals and added consistent visual CSS')
