(()=>{
  const scenes=[...document.querySelectorAll('.scene')];const assets=['dream-theatre-panorama.jpg','dream-choices.png','dream-conversations.png'];
  scenes.forEach((scene,i)=>{
    if(i>0){const orbit=document.createElement('div');orbit.className='dream-orbit';orbit.innerHTML=orbitSteps(scene).map((x,n)=>`<span><i>${['IF','→','?'][n]}</i>${x}</span>`).join('');const head=scene.querySelector('.head');head?.insertAdjacentElement('afterend',orbit)}
    if(i>0&&!scene.querySelector('img')){const mode=i%3;const variants=['portal-wide','portal-left','portal-right'];const asset=mode===0?assets[0]:assets[mode];const fig=document.createElement('figure');fig.className=`dream-portal ${variants[mode]}`;fig.innerHTML=`<img src="assets/${asset}" alt="Imaginary world used as a prompt for a second conditional task."><figcaption>${caption(scene)}</figcaption>`;const orbit=scene.querySelector('.dream-orbit');const content=scene.querySelector('.grid,.timeline,.formula,.feedback,.board,.cards');if(mode===0&&orbit)orbit.after(fig);else if(mode===1&&content)content.after(fig);else if(scene.querySelector('.feedback'))scene.querySelector('.feedback').before(fig);else if(content)content.before(fig);else orbit?.after(fig)}
  });
  const controls=document.querySelector('.controls'),next=document.querySelector('#next');const info=document.createElement('button');info.id='v2Info';info.className='nav v2-control';info.textContent='i · DREAM INFO';const full=document.createElement('button');full.id='v2Full';full.className='nav v2-control';full.textContent='⛶ · FULL';controls?.insertBefore(info,next);controls?.insertBefore(full,next);
  const panel=document.createElement('section');panel.className='v2-panel';panel.innerHTML='<div class="v2-panel-card"><button class="v2-close" aria-label="Close task panel">×</button><h3>Dream scene</h3><p class="v2-note"></p><ol><li>Imagine the IF situation.</li><li>Build the result with WOULD + base verb.</li><li>Add one reason, detail, or follow-up question.</li></ol></div>';document.body.append(panel);
  const open=()=>{const s=document.querySelector('.scene.active');panel.querySelector('h3').textContent=s?.dataset.title||'Dream scene';panel.querySelector('.v2-note').textContent=s?.querySelector('.teacher')?.textContent.trim()||caption(s);panel.classList.add('open')};info.onclick=open;panel.querySelector('.v2-close').onclick=()=>panel.classList.remove('open');panel.onclick=e=>{if(e.target===panel)panel.classList.remove('open')};full.onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='i')open();if(e.key==='Escape')panel.classList.remove('open')});
  const counter=document.querySelector('#counter'),fill=document.querySelector('#fill');const sync=()=>{const n=parseInt(counter?.textContent)||1;fill?.style.setProperty('width',(n/scenes.length*100)+'%','important');fill?.style.setProperty('height','100%','important')};new MutationObserver(sync).observe(counter,{childList:true,subtree:true,characterData:true});sync();
  const requested=Number(location.hash.slice(1));if(Number.isInteger(requested)&&requested>1&&requested<=scenes.length){for(let n=1;n<requested;n++)document.querySelector('#next')?.click();scenes[requested-1].style.animation='none'}
  function orbitSteps(s){const t=s?.dataset.title||'';if(/Reading|Detail/.test(t))return['Find the imagined condition','Find the result or evidence','Explain how the two halves connect'];if(/Speaking|Gap|Production/.test(t))return['Choose a dream situation','Answer with would + base verb','Ask why or add a consequence'];if(/Form|Practice|Notice|Meaning/.test(t))return['Locate the IF half','Check the verb form','Explain whether it is dream or advice'];return['Enter one imaginary situation','Describe what would happen','Add one memorable detail']}
  function caption(s){const t=s?.dataset.title||'';if(/Advice|Were|Notice/.test(t))return'If I were you… opens a careful advice scene.';if(/Reading/.test(t))return'Read the imagined world, then trace condition to result.';if(/Production|Speaking/.test(t))return'Invent freely, but keep the grammar doorway stable.';return'One imagined condition can open many possible results.'}
})();
